using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using Mapo.Generator.Models;

namespace Mapo.Generator.Emit;

public static class MapperEmitter
{
    public static string Emit(MapperInfo mapper)
    {
        var methodPatterns = new List<(string MethodName, Regex GroupPattern, Regex CallPattern)>();
        foreach (var mapping in mapper.Mappings)
        {
            if (mapping.IsEnumMapping)
                continue;
            var methodName = mapping.MethodName;
            var groupPattern = new Regex($@"(?<!\w|\.){Regex.Escape(methodName)}(?!\w|\s*\()");
            var callPattern = new Regex($@"(?<!\w|\.){Regex.Escape(methodName)}\s*\(");
            methodPatterns.Add((methodName, groupPattern, callPattern));
        }

        var cw = new CodeWriter();

        cw.AppendLine("// <auto-generated />");
        cw.AppendLine("#nullable enable");
        cw.AppendLine("using System;");
        cw.AppendLine("using System.CodeDom.Compiler;");
        cw.AppendLine("using System.Collections.Generic;");
        cw.AppendLine("using System.Linq;");
        cw.AppendLine("using System.Runtime.CompilerServices;");
        cw.AppendLine("using System.Threading;");
        cw.AppendLine("using System.Threading.Tasks;");
        cw.AppendLine("using Mapo.Attributes;");
        bool hasNamespace = !string.IsNullOrEmpty(mapper.Namespace) && mapper.Namespace != "<global namespace>";
        if (hasNamespace)
        {
            cw.AppendLine($"namespace {mapper.Namespace};");
        }
        cw.AppendLine();

        cw.AppendLine("[GeneratedCode(\"Mapo.Generator\", \"1.0.0\")]");
        cw.AppendLine($"{(mapper.IsStatic ? "static " : "")}partial class {mapper.ClassName}");
        using (cw.Block())
        {
            foreach (var mapping in mapper.Mappings)
            {
                var paramsList = string.Join(", ", mapping.Parameters);

                if (mapping.IsEnumMapping)
                {
                    cw.AppendLine(
                        "[MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]"
                    );
                    EnumEmitter.Emit(cw, mapping, mapper.IsStatic, paramsList);
                }
                else if (mapping.IsCollectionMapping)
                {
                    CollectionEmitter.Emit(cw, mapping, mapper, methodPatterns);
                }
                else
                {
                    ObjectEmitter.Emit(cw, mapping, mapper, methodPatterns);
                }
            }
        }

        var extensionMappings = mapper
            .Mappings.Where(m => m.IsUserDeclared && m.Parameters.Count == 1 && !m.IsEnumMapping && mapper.IsStatic)
            .ToList();

        if (extensionMappings.Count > 0)
        {
            cw.AppendLine();
            cw.AppendLine("[GeneratedCode(\"Mapo.Generator\", \"1.0.0\")]");
            cw.AppendLine($"public static class {mapper.ClassName}Extensions");
            using (cw.Block())
            {
                foreach (var mapping in extensionMappings)
                {
                    var sourceType = mapping.SourceTypeDisplayString;
                    var targetType = mapping.TargetTypeDisplayString;

                    cw.AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
                    cw.AppendLine($"public static {targetType} {mapping.MethodName}(this {sourceType} source)");
                    using (cw.Block())
                    {
                        cw.AppendLine($"return {mapper.ClassName}.{mapping.MethodName}(source);");
                    }

                    cw.AppendLine();
                    cw.AppendLine(
                        $"public static async IAsyncEnumerable<{targetType}> {mapping.MethodName}StreamAsync(this IAsyncEnumerable<{sourceType}> source, [EnumeratorCancellation] CancellationToken ct = default)"
                    );
                    using (cw.Block())
                    {
                        var mapperCall = $"{mapper.ClassName}.{mapping.MethodName}(item)";
                        cw.AppendLine($"await foreach (var item in source.WithCancellation(ct))");
                        using (cw.Block())
                        {
                            cw.AppendLine($"yield return {mapperCall};");
                        }
                    }
                }
            }
        }

        return cw.ToString();
    }
}
